test:
	./node_modules/.bin/mocha \
		--reporter list \
		--compilers coffee:coffee-script

guard:
	./node_modules/.bin/mocha \
		--watch \
		--reporter dot \
		--compilers coffee:coffee-script

.PHONY: test
